workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - firebase_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA for Firebase
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist || flutter build ios --release
      - name: Create IPA manually if needed
        script: |
          if [ ! -f build/ios/ipa/*.ipa ]; then
            cd build/ios/iphoneos
            mkdir -p Payload
            cp -r Runner.app Payload/
            zip -r ../../../app.ipa Payload
            mkdir -p ../ipa
            mv ../../../app.ipa ../ipa/
          fi
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        ios:
          app_id: $FIREBASE_IOS_APP_ID
          groups:
            - testers